### ISSUE TITLE
HiSCR50, HiSCR75, and HiSCR90 (Hidradenitis Suppurativa Clinical Response):

### ISSUE THREAD

**Issue by DBartlettHP** [billdenney/hidradenitis#3]
At least a 50%, 75%, or 90% reduction in the total abscess and inflammatory nodule count, AND
No increase in abscess count, AND
No increase in draining fistula count.

Compared to baseline.

Output will be Binary for if this response is achieved or not.

**Comment by billdenney** [comment]
This looks good.  What you described is the HiSCR50 (50 is a 50% decrease).  Can you please also generalize so that it will accept other percentages?

More recently, HiSCR75 and occasionally 90 have been used.

**Comment by DBartlettHP** [comment]
(This seems true for most of the assessments)
In order to calculate accurately, the data will need to the following information:
- SUBJID
- Visit Day (To discern between baseline and response)
- Abscess count
- Inflammatory Nodule count
- Draining Fistula count

I am exploring ways to map the last three ideas to potential SDTM columns, if you have any ideas.
(Do you think these would be found in an SDTM "FA" domain?)

[FA](https://www.mycsg.in/meta_sdtm_var_master.php?domain=FA) - [Findings About Events or Interventions](https://www.mycsg.in/meta_sdtm_examples.php?domain=FA)

FATEST - findings about test name (ex. Count, Volume, Number of episodes, Severity, etc)

FAOBJ - Describes the object or focal point (ex. Abscess Count, Vomit, Nausea, etc)

FASTRESN - Result or findings in numerical (ex. 0, >10, etc)

**Comment by billdenney** [comment]
Let's separate the concerns of calculation from the SDTM itself.  Can you make it so that this function takes in:

1. abscess count, inflammatory nodule count, and draining fistula count at baseline (3 arguments),
2. abscess count, inflammatory nodule count, and draining fistula count at the time point of interest (3 more arguments),
3. The percentage required (e.g. 50 for HiSCR50, 75 for HiSCR75, etc.)

Then, the user would need to setup the data so that those 6 parameters could be passed in to the function.  In SDTM, these six parameters would likely come as separate rows, so it will take some degree of data management to convert to the format required for input, anyway.

**Comment by billdenney** [comment]
Completed in #8
